"use client";

import MatchCard from "./components/MatchCard";

const matches = [
    {
        homeTeam: { name: "Persepolis" },
        awayTeam: { name: "Tractor" },
        homeScore: 1,
        awayScore: 1,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Azadi",
        date: "2026/08/01",
    },
    {
        homeTeam: { name: "Esteghlal" },
        awayTeam: { name: "Sepahan" },
        homeScore: 2,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Azadi",
        date: "2026/08/02",
    },
    {
        homeTeam: { name: "Foolad" },
        awayTeam: { name: "Gol Gohar" },
        homeScore: 3,
        awayScore: 2,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Ahvaz",
        date: "2026/08/03",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },
    {
        homeTeam: { name: "Malavan" },
        awayTeam: { name: "Aluminium" },
        homeScore: 0,
        awayScore: 0,
        tournament: "Iran Pro League",
        round: "Week 1",
        stadium: "Anzali",
        date: "2026/08/04",
    },

];
export default function Page() {
    return (
        <div className="py-2">

            <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
                {matches.map((match, index) => (
                    <MatchCard
                        key={index}
                        homeTeam={match.homeTeam}
                        awayTeam={match.awayTeam}
                        homeScore={match.homeScore}
                        awayScore={match.awayScore}
                        tournament={match.tournament}
                        round={match.round}
                        stadium={match.stadium}
                        date={match.date}
                    />
                ))}
            </div>

        </div>
    );
}